# Site settings
title: Death Metal Family Radio
email: your-email@domain.com
description: "Death Metal Family Radio Hour and Death Metal Podcast for Kids were written for IndyFringe and submitted by Bloomington Playwrights Project."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jessicareed
github_username:  jessicareed

# Build settings
markdown: kramdown
permalink: pretty
